name: danapaniexpress
description: "Dana Pani Express - Grocery App for Pakistani Market"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #  Other packages
  carousel_slider: ^5.0.0
  scrollable_positioned_list: ^0.3.8

  #  Images and animations
  flutter_svg: ^2.0.16
  lottie: ^3.2.0
  marquee: ^2.3.0
  animate_do: ^4.2.0
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1

  # URL launches and pdf library and navigations
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  clipboard: ^0.1.3

  # Files Downloading and manipulating
  dio: ^5.7.0
  http: ^1.2.2
  permission_handler:

  #  Mobile ads
  #  google_mobile_ads: ^5.2.0

  # database packages
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

  #  localization, translation, date formats
  intl: ^0.20.1

  #  State management
  get: ^4.6.6

  #  internet connection check
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/common/
   - assets/common/anims/
   - assets/common/icons/
   - assets/common/images/
   - assets/dev/
   - assets/dev/anims/
   - assets/dev/icons/
   - assets/dev/images/
   - assets/prod/
   - assets/prod/anims/
   - assets/prod/icons/
   - assets/prod/images/
   - assets/rider/
   - assets/rider/anims/
   - assets/rider/icons/
   - assets/rider/images/

  fonts:
    - family: inter_regular
      fonts:
        - asset: fonts/Inter-Regular.ttf

    - family: noto_nastaliq_regular
      fonts:
        - asset: fonts/NotoNastaliqUrdu-Regular.ttf

    - family: noto_nastaliq_semibold
      fonts:
        - asset: fonts/NotoNastaliqUrdu-SemiBold.ttf

    - family: nunito_medium
      fonts:
        - asset: fonts/Nunito-Medium.ttf

    - family: nunito_semibold
      fonts:
        - asset: fonts/Nunito-SemiBold.ttf

    - family: poppins_bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: poppins_regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: poppins_semibold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: roboto_regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: oswald_regular
      fonts:
        - asset: fonts/Oswald-Regular.ttf

    - family: oswald_semibold
      fonts:
        - asset: fonts/Oswald-SemiBold.ttf

    - family: faiz_lahore_nastaleeq
      fonts:
        - asset: fonts/faiz-lahori-nastaleeq-regular.ttf

