
///FONT SIZES
const INDEX_FONT_SIZE = 20.0;
const HEADING_FONT_SIZE = 18.0;
const PRIMARY_HEADING_FONT_SIZE = 26.0;
const SECONDARY_HEADING_FONT_SIZE = 24.0;
const NORMAL_TEXT_FONT_SIZE = 16.0;
const SUB_HEADING_TEXT_BUTTON_FONT_SIZE = 14.0;
const CONTENT_TEXT_FONT_SIZE = 18.0;
const TAGS_FONT_SIZE = 12.0;
const RATING_FONT_SIZE = 12.0;
const DATE_TIME_FONT_SIZE = 12.0;
const SUBSCRIPTION_TITLE_FONT_SIZE = 22.0;
const LUGHAT_HEADING_FONT_SIZE = 22.0;
const LUGHAT_SUB_HEADING_FONT_SIZE = 18.0;
const PROGRESS_FONT_SIZE = 8.0;

const SMALL_TEXT_FONT_SIZE = 16.0;
const MEDIUM_TEXT_FONT_SIZE = 20.0;
const LARGE_TEXT_FONT_SIZE = 24.0;
const SPLASH_HEADING_TEXT_FONT_SIZE = 50.0;


///PADDINGS AND OTHER SIZES

const MAIN_HORIZONTAL_PADDING = 14.0;
const MAIN_VERTICAL_PADDING = 20.0;
const LIST_ITEM_HEIGHT = 48.0;
const BUTTON_HEIGHT = 48.0;
const BOTTOM_NAV_BAR_SIZE = 90.0;

/// ANIMATION DURATION
const SCREEN_ANIMATION_DURATION = 300;